name: Test React

on:
  push:
    paths:
      - client/**
    #branches: 
    #  - main
    tags:
      - "v*"
  pull_request:
    paths:
      - client/**
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: cache-node_modules
        uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: './client/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      
      - name: npm-install
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        working-directory: ./client
        run: npm i
      
      - name: run test
        working-directory: ./client
        env:
          CI: 'true'
        run: npm test
